clear_history:
  fields:
    days_to_keep:
      required: true
      example: 30
      selector:
        number:
          min: 1
          max: 365
          unit_of_measurement: days

generate_dashboard:
  fields:
    include_status_card:
      default: true
      selector:
        boolean:
    include_downstream_power:
      default: true
      selector:
        boolean:
    include_downstream_snr:
      default: true
      selector:
        boolean:
    include_downstream_frequency:
      default: true
      selector:
        boolean:
    include_upstream_power:
      default: true
      selector:
        boolean:
    include_upstream_frequency:
      default: true
      selector:
        boolean:
    include_errors:
      default: true
      selector:
        boolean:
    include_latency:
      default: true
      selector:
        boolean:
    graph_hours:
      default: 24
      selector:
        number:
          min: 1
          max: 168
          unit_of_measurement: hours
    short_titles:
      default: true
      selector:
        boolean:
